name: cyrs
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.0-231.0.dev

dependencies:
  archive: ^4.0.7
  file_picker: ^10.3.7
  flutter:
    sdk: flutter
  flutter_html: ^3.0.0
  http: ^1.6.0
  image_picker: ^1.0.4
  intl: ^0.20.2
  pdfx: ^2.9.2
  shared_preferences: ^2.5.3
  supabase_flutter: ^2.12.2
  app_links: ^7.0.0
  webview_flutter: ^4.13.0
  mailer: ^6.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_animate: ^4.5.2
  cached_network_image: ^3.2.3

flutter:
  uses-material-design: true
